# Generated by Django 2.1.2 on 2019-05-16 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('mac', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartPlug',
            fields=[
                ('serial_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.Coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='SmartPlugOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.IntegerField(choices=[(1, 'coordinator'), (2, 'family'), (3, 'guest')])),
                ('name', models.CharField(max_length=32)),
                ('smartplug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Coordinator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
