# Generated by Django 2.1.2 on 2019-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20190516_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartplugowner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
