# Generated by Django 2.1.2 on 2019-05-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_auto_20190516_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplugowner',
            name='status',
            field=models.IntegerField(choices=[(0, 'disconnect'), (1, 'on'), (2, 'off')], default=0),
        ),
    ]
