# Generated by Django 2.1.2 on 2019-05-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_auto_20190517_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartplug',
            name='status',
            field=models.IntegerField(choices=[(2, 'disconnect'), (1, 'on'), (0, 'off')], default=2),
        ),
    ]
