# Generated by Django 2.1.2 on 2019-05-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20190516_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartplugowner',
            name='smartplug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.SmartPlug'),
        ),
    ]
